output_dir: "/mnt/gtklab01/xiaoqing"

samples: ../snakemake_dataprocess/config/samples.tsv
tags: ["d", "m1", "m2", "u"]

dirs_tag:
  full: "full"
  mashmap: "mashmap"
  addition: "analysis"

Params:
  threads: 8