Paths:
  gtffile: "/mnt/gtklab01/linglab/mmusculus_annotation_files/gencode.vM29.primary_assembly.annotation.gtf"
  genomefile: "/mnt/gtklab01/linglab/mmusculus_annotation_files/GRCm39.primary_assembly.genome.fa"
  chromsize: "/mnt/gtklab01/linglab/mmusculus_annotation_files/GRCm39.chrNameLength.txt"

output_dir: "/mnt/gtklab01/gtk/decoys/2024-12-20"

transcript_type: protein_coding

mashmap: "/mnt/cbis/home/e1124735/bin/mashmap"

Params:
  threads: 8