output_dir: "/mnt/gtklab01/xiaoqing"

samples: ./subworkflows/snakemake_dataprocess/config/samples.tsv
tags: ["d", "m1", "m2", "u"]
RNA_READS_DIR: "/mnt/gtklab01/linglab/tdp43/geo"

Paths:
  gtffile: "/mnt/gtklab01/linglab/mmusculus_annotation_files/gencode.vM29.primary_assembly.annotation.gtf"
  genomefile: "/mnt/gtklab01/linglab/mmusculus_annotation_files/GRCm39.primary_assembly.genome.fa"
  chromsize: "/mnt/gtklab01/linglab/mmusculus_annotation_files/GRCm39.chrNameLength.txt"

subworkflows:
  A: "subworkflows/snakemake_decoygenerate/config/config.yaml"
  B: "subworkflows/snakemake_dataprocess/config/config.yaml"
  C: "subworkflows/snakemake_analysis/config/config.yaml"

dirs_tag:
  full: "full"
  mashmap: "mashmap"
  addition: "analysis"

snakemake_A_outputs:
  - "gentrom.fa"
  - "decoy.txt"
  - "genemap.tsv"

snakemake_B_outputs:
  samples_tsv: "samples.tsv"

