Files:
  gtffile: "/mnt/gtklab01/linglab/mmusculus_annotation_files/gencode.vM29.primary_assembly.annotation.gtf"
  genomefile: "/mnt/gtklab01/linglab/mmusculus_annotation_files/GRCm39.primary_assembly.genome.fa"
  chromsize: "/mnt/gtklab01/linglab/mmusculus_annotation_files/GRCm39.chrNameLength.txt"
  stargenome: "/mnt/gtklab01/linglab/mmusculus_annotation_files/STAR_v2.7.9a_index_mmusculus_gencode.vM29"

src_dir: "/mnt/cbis/home/gtk/src/xiaoqing-capstone/src/scripts"
decoy_dir: "/mnt/gtklab01/xiaoqing/decoys"
output_dir: "/mnt/gtklab01/xiaoqing"
RNA_READS_DIR: "/mnt/gtklab01/linglab/tdp43/geo"

samples: ./config/samples.tsv
tags: ["d", "m1", "m2", "u"]
